"""Deterministic fixtures generated by running scenarios through the real engine.

    python -m table_tennis.sim.fixtures           # (re)write tests/table_tennis/fixtures/*.json
    python -m table_tennis.sim.fixtures --check   # fail if fixtures are stale

Uses FixedClock + SequentialIdGenerator so output is byte-for-byte stable.
"""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path

from table_tennis.config import load_settings
from table_tennis.core.ports import FixedClock, SequentialIdGenerator

from .driver import InProcessDriver
from .scenarios import FIXTURE_SCENARIOS, SCENARIOS

REPO_ROOT = Path(__file__).resolve().parents[2]
FIXTURE_DIR = REPO_ROOT / "tests" / "table_tennis" / "fixtures"


def make_runtime(tmpdir: str):
    from table_tennis.api.runtime import build_runtime

    settings = load_settings(
        env={},
        storage__db_path=str(Path(tmpdir) / "fixture.sqlite"),
        outputs__fake_log_path="",
    )
    ids = SequentialIdGenerator()
    runtime = build_runtime(settings, clock=FixedClock(), ids=ids, background=False)
    runtime.start()
    return runtime, ids


def run_fixture(name: str) -> dict:
    with tempfile.TemporaryDirectory() as tmp:
        runtime, ids = make_runtime(tmp)
        try:
            driver = InProcessDriver(runtime, ids=ids)
            SCENARIOS[name](driver)
            events = []
            if driver.match_id:
                for cursor, e in runtime.store.read_after(driver.match_id, 0, limit=100000):
                    events.append({"cursor": cursor, "event": json.loads(e.model_dump_json())})
            final = driver.snapshot() if driver.match_id else None
            return {
                "name": name,
                "description": (SCENARIOS[name].__doc__ or "").strip() or None,
                "schema_version": "1.0",
                "generated_by": "python -m table_tennis.sim.fixtures",
                "steps": driver.steps,
                "events": events,
                "final_snapshot": final,
            }
        finally:
            runtime.stop()


def render_all() -> dict[Path, str]:
    return {
        FIXTURE_DIR / f"{name}.json": json.dumps(run_fixture(name), indent=2, ensure_ascii=False) + "\n"
        for name in FIXTURE_SCENARIOS
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    stale = []
    for path, content in render_all().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            stale.append(path.name)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8", newline="\n")
    if args.check:
        if stale:
            print("STALE fixtures: " + ", ".join(stale) + " (run python -m table_tennis.sim.fixtures)")
            return 1
        print("fixtures are up to date")
        return 0
    print("wrote: " + (", ".join(stale) if stale else "nothing (up to date)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
