#!/usr/bin/env bash
# =============================================================================
# setup_network_manager_sudoers.sh
#
# Adds the sudoers rules required for the robot supervisor's Network Manager
# feature (POST /api/network/connections and related endpoints).
#
# Run once as root:
#   sudo bash setup_network_manager_sudoers.sh
#
# ─── What this script does ───────────────────────────────────────────────────
#  1. Writes ONE new file: /etc/sudoers.d/robot-supervisor-network
#  2. Validates it with `visudo -c` before making it active — aborts if invalid
#  3. Does NOT modify /etc/sudoers or any other existing sudoers file
#  4. Does NOT change any network interface, IP, route, or firewall rule
#  5. Does NOT start, stop, or restart any service
#
# ─── Why each rule is needed ─────────────────────────────────────────────────
#  nmcli connection add  — create a new wifi profile (no interface is touched yet)
#  nmcli conn up         — activate a wifi profile (connects to an AP)
#  nmcli conn down       — deactivate a wifi profile (disconnects from AP)
#  nmcli conn delete     — remove a stored wifi profile
#
#  The supervisor application enforces that only 802-11-wireless connections
#  may be passed to up/down/delete, so ethernet, docker bridges, loopback, and
#  VPN adapters are protected at the application layer.  These sudoers rules
#  give the technical ability to call nmcli; the application restricts what
#  connection types are allowed.
#
# ─── Variables ───────────────────────────────────────────────────────────────
#  SUPERVISOR_USER  — OS user that runs the robot supervisor (default: unitree)
#  Override with:  sudo SUPERVISOR_USER=myuser bash setup_network_manager_sudoers.sh
# =============================================================================

set -euo pipefail

SUDOERS_FILE="/etc/sudoers.d/robot-supervisor-network"
SUPERVISOR_USER="${SUPERVISOR_USER:-unitree}"

# ── Preflight checks ──────────────────────────────────────────────────────────

if [[ "$EUID" -ne 0 ]]; then
  echo "ERROR: this script must be run as root (use sudo)." >&2
  exit 1
fi

# Detect nmcli — must be the absolute path for sudoers
NMCLI_PATH="$(command -v nmcli 2>/dev/null || true)"
if [[ -z "$NMCLI_PATH" || ! -x "$NMCLI_PATH" ]]; then
  echo "ERROR: nmcli not found. Is NetworkManager installed?" >&2
  exit 1
fi

# Confirm the user exists
if ! id "$SUPERVISOR_USER" &>/dev/null; then
  echo "ERROR: user '$SUPERVISOR_USER' does not exist on this system." >&2
  exit 1
fi

# Reject suspicious nmcli path (should always be /usr/bin/nmcli on Linux)
if [[ "$NMCLI_PATH" != /usr/bin/nmcli && "$NMCLI_PATH" != /bin/nmcli ]]; then
  echo "WARNING: unexpected nmcli path: $NMCLI_PATH"
  read -r -p "Continue anyway? [y/N] " ans
  [[ "${ans,,}" == "y" ]] || { echo "Aborted."; exit 1; }
fi

# ── Write rules to a temp file and validate before installing ────────────────

TMPFILE="$(mktemp /tmp/sudoers-nm-XXXXXX)"
trap 'rm -f "$TMPFILE"' EXIT

cat > "$TMPFILE" << EOF
# Robot Supervisor – Network Manager sudoers rules
# Generated by setup_network_manager_sudoers.sh
# Re-run the script to regenerate; do not edit manually.
#
# Only WiFi-related nmcli sub-commands are listed here.  The application
# enforces an additional check (nmcli -g TYPE) before calling up/down to
# ensure only 802-11-wireless connections are ever touched.

# Add a new WiFi connection profile (does not activate it yet)
${SUPERVISOR_USER} ALL=(root) NOPASSWD: ${NMCLI_PATH} connection add type wifi *

# Activate / deactivate a WiFi connection profile
${SUPERVISOR_USER} ALL=(root) NOPASSWD: ${NMCLI_PATH} conn up *
${SUPERVISOR_USER} ALL=(root) NOPASSWD: ${NMCLI_PATH} conn down *

# Delete a stored WiFi connection profile
${SUPERVISOR_USER} ALL=(root) NOPASSWD: ${NMCLI_PATH} conn delete *
${SUPERVISOR_USER} ALL=(root) NOPASSWD: ${NMCLI_PATH} connection delete *
EOF

echo "Validating sudoers syntax ..."
if ! visudo -cf "$TMPFILE"; then
  echo "ERROR: visudo validation failed — no changes made." >&2
  exit 1
fi

# ── Install ──────────────────────────────────────────────────────────────────

cp "$TMPFILE" "$SUDOERS_FILE"
chmod 0440 "$SUDOERS_FILE"
chown root:root "$SUDOERS_FILE"

echo ""
echo "✓ Installed: $SUDOERS_FILE"
echo ""
echo "Active rules:"
grep -v '^#' "$SUDOERS_FILE" | grep -v '^$'
echo ""
echo "No existing network configuration was modified."
echo "No network interfaces were changed."
