#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
PYTHON="${REPO_ROOT}/.venv/bin/python"

if [[ ! -x "${PYTHON}" ]]; then
  PYTHON="python3"
fi

ARGS=()
RELAXED=0
for arg in "$@"; do
  if [[ "${arg}" == "--relaxed" ]]; then
    RELAXED=1
  elif [[ "${arg}" == "--portrait" ]]; then
    ARGS+=("--portrait-debug")
  else
    ARGS+=("${arg}")
  fi
done

if [[ "${RELAXED}" == "1" ]]; then
  export VISION_CARD_CAPTURE_MIN_AREA_RATIO="${VISION_CARD_CAPTURE_MIN_AREA_RATIO:-0.04}"
  export VISION_CARD_CAPTURE_MIN_BLUR="${VISION_CARD_CAPTURE_MIN_BLUR:-25}"
  export VISION_CARD_CAPTURE_STABILITY_FRAMES="${VISION_CARD_CAPTURE_STABILITY_FRAMES:-2}"
  export VISION_CARD_CAPTURE_MAX_BRIGHTNESS="${VISION_CARD_CAPTURE_MAX_BRIGHTNESS:-245}"
  export VISION_CARD_CAPTURE_MAX_GLARE_RATIO="${VISION_CARD_CAPTURE_MAX_GLARE_RATIO:-0.35}"
else
  export VISION_CARD_CAPTURE_MIN_AREA_RATIO="${VISION_CARD_CAPTURE_MIN_AREA_RATIO:-0.08}"
  export VISION_CARD_CAPTURE_MIN_BLUR="${VISION_CARD_CAPTURE_MIN_BLUR:-80}"
  export VISION_CARD_CAPTURE_STABILITY_FRAMES="${VISION_CARD_CAPTURE_STABILITY_FRAMES:-3}"
fi
export VISION_CARD_CAPTURE_JPEG_QUALITY="${VISION_CARD_CAPTURE_JPEG_QUALITY:-90}"
export VISION_CARD_CAPTURE_OUTPUT_WIDTH="${VISION_CARD_CAPTURE_OUTPUT_WIDTH:-856}"
export VISION_CARD_CAPTURE_OUTPUT_HEIGHT="${VISION_CARD_CAPTURE_OUTPUT_HEIGHT:-540}"

exec "${PYTHON}" "${SCRIPT_DIR}/local_id_capture.py" "${ARGS[@]}"
