#!/usr/bin/env python3
"""
a2_nav_stream.py — live NAVIGATION telemetry for the Supervisor's Navigation tab.

WHAT THIS STREAMS
-----------------
Four things the nav stack publishes, none of which are usable over HTTP-RPC:

    pose    live map->base_link pose, from /tf (fallback: /slam/localization/odometry)
    path    the ACTUAL planned polyline, from /pnc/path_publish
    avoid   replan / blocked events, from /pnc/avoid_status
    state   pnc service state, from /pnc/service_state

WHY POSE COMES FROM HERE AND NOT FROM TransFormService (settled 2026-09-09)
---------------------------------------------------------------------------
`TransFormService/GetTransFormation{map, base_link}` is registered on the gateway but
is BROKEN on this build: it returns an empty body and blocks until the client's
timeout, whether or not localization has converged. Verified with the robot standing,
localized, and freshly relocalized from the tablet — still a 10 s hang.

The pose is fine; only that RPC is broken. slam publishes it to ROS 2 natively:
    /tf                            tf2_msgs/msg/TFMessage   <- carries map->base_link
    /slam/localization/odometry    nav_msgs/msg/Odometry    <- same pose, frame "map"
Note these are registered WITHOUT the `pb_...` name mangling the pnc topics use
(the slam log says "register publish type for topic '/tf' success." with no "real
ros2 topic name is"), which is the tell that they are REAL ROS types, not
protobuf-in-a-wrapper. So they need no protobuf decode at all.

Measured working: `/tf` map->base_link x=0.038 y=0.001 yaw=0.418, and
`/slam/localization/odometry` header.frame_id="map".

It is READ-ONLY. It subscribes to topics that are already being published and never
commands the robot.

WHY A SIDECAR PROCESS (same reason as a2_costmap.py)
-----------------------------------------------------
The supervisor runs on the repo `.venv`, which is python3.12 and has **no rclpy**.
rclpy exists only on system python3.10 with /opt/ros/humble sourced. So this runs as
its own process, speaks NDJSON on stdout, and the supervisor relays it. It also runs
standalone for debugging:  `python3 a2_nav_stream.py --pretty`

FOUR THINGS THAT MAKE THIS NON-OBVIOUS (all measured 2026-09-08)
-----------------------------------------------------------------
1. THE TOPIC NAME IS MANGLED. AimRT's ros2 plugin does not publish `/pnc/path_publish`
   as-is; it appends the protobuf type, giving
       /pnc/path_publish/pb_3Aaimdk_2Eprotocol_2EPncPathChannel
   (`3A` = ':', `2E` = '.', percent-style). Get this wrong and you subscribe
   successfully to a topic nobody publishes, with no error. The authoritative list is
   in the pnc log:
       grep -a "register publish type for topic" /agibot/log/pnc/running_planning.log

2. THE MESSAGE TYPE IS A GENERIC WRAPPER, NOT A TYPED ROS MESSAGE.
   Everything arrives as `ros2_plugin_proto/msg/RosMsgWrapper`
   (`string serialization_type`, `string[] context`, `byte[] data`) with
   serialization_type == "pb" and `data` holding the serialized protobuf. That
   package is not in /opt/ros; it ships inside the aima-cli venv, hence PB_DEPS below.

3. `msg.data` IS A LIST OF 1-BYTE `bytes` OBJECTS in rclpy, not a buffer.
   `bytes(msg.data)` raises TypeError. Use b"".join(...) — see _payload().

4. THE PUBLISHERS ARE BEST_EFFORT. Subscribing RELIABLE (rclpy's default for a plain
   depth) makes DDS log "incompatible QoS ... No messages will be received" once and
   then sit silent forever. Must be BEST_EFFORT.

WHY protoc RUNS AT STARTUP
--------------------------
The SDK ships pre-generated `*_pb2.py` under
`<aima-cli>/share/protocol/py/`, but those were generated by a NEWER protoc and do
`from google.protobuf.internal import builder`, which does not exist in this box's
protobuf runtime (3.12.4) — importing them raises ImportError. The system `protoc` is
also 3.12.4, so regenerating from the shipped .proto files produces bindings that DO
import. It takes ~0.2 s for all 210 protos, so this regenerates on every start into a
temp dir rather than vendoring generated code that could silently drift from the
firmware's protos.

"""
from __future__ import annotations

import argparse
import json
import math
import os
import shlex
import subprocess
import sys
import tempfile
import time

# ---------------------------------------------------------------- ROS bootstrap
# Identical to a2_costmap.py / a2_lidar.py. See a2_costmap.py for the full
# rationale: .bashrc pins ROS_DOMAIN_ID=231 but the robot stack is on 232, and an
# un-forced domain yields ZERO topics with no error message at all.

ROS_SETUP = "/opt/ros/humble/setup.bash"
DDS_PROFILE = "/agibot/software/v0/entry/bin/cfg/ros_dds_configuration.xml"
ROS_DOMAIN_ID = "232"

# Where the aima SDK keeps the ros2_plugin_proto rosidl package (the RosMsgWrapper
# message) and the .proto sources we regenerate from.
PB_DEPS = ("/opt/pipx/venvs/aima-cli/lib/python3.10/site-packages/aima/core/"
           "deps_ensure/aimrte_tools_newsm")
PROTO_SRC = f"{PB_DEPS}/share/protocol/proto"
ROSIDL_PY = f"{PB_DEPS}/local/lib/python3.10/dist-packages"

_dom = os.environ.get("A2_ROS_DOMAIN_ID")
for _i, _a in enumerate(sys.argv):
    if _a == "--domain" and _i + 1 < len(sys.argv):
        _dom = sys.argv[_i + 1]
    elif _a.startswith("--domain="):
        _dom = _a.split("=", 1)[1]
os.environ["ROS_DOMAIN_ID"] = _dom or ROS_DOMAIN_ID
os.environ["ROS_LOCALHOST_ONLY"] = "0"
os.environ["RMW_IMPLEMENTATION"] = "rmw_fastrtps_cpp"
if os.path.exists(DDS_PROFILE):
    os.environ["FASTRTPS_DEFAULT_PROFILES_FILE"] = DDS_PROFILE
# The rosidl typesupport .so files for ros2_plugin_proto live in the aima venv.
os.environ["AMENT_PREFIX_PATH"] = (
    PB_DEPS + os.pathsep + os.environ.get("AMENT_PREFIX_PATH", ""))
os.environ["LD_LIBRARY_PATH"] = (
    f"{PB_DEPS}/lib" + os.pathsep + os.environ.get("LD_LIBRARY_PATH", ""))

# The interpreter to re-exec into. MUST be spelled out rather than left as bare
# `python3`: the supervisor is launched with `source .venv/bin/activate`, which puts
# .venv/bin (python3.12, no rclpy) FIRST on PATH. A bare `python3` inside the
# bootstrap then re-exec'd straight back into 3.12 and the guard below aborted with
# "rclpy still unavailable after sourcing ROS" — which is exactly how this failed
# when spawned from the supervisor while working fine from an interactive shell.
SYS_PYTHON = "/usr/bin/python3"          # 3.10.12, the one with rclpy

try:
    import rclpy  # noqa: F401
except ImportError:
    if os.environ.get("_A2_NAVSTREAM_BOOTSTRAPPED") == "1":
        sys.exit(f"rclpy still unavailable after sourcing ROS via {SYS_PYTHON}. "
                 f"Check that /opt/ros/humble is installed for that interpreter.")
    os.environ["_A2_NAVSTREAM_BOOTSTRAPPED"] = "1"
    # Also drop the venv markers, so nothing downstream re-resolves to python3.12.
    os.environ.pop("VIRTUAL_ENV", None)
    os.environ.pop("PYTHONHOME", None)
    os.environ.pop("PYTHONPATH", None)
    _py = SYS_PYTHON if os.path.exists(SYS_PYTHON) else "python3"
    _args = " ".join(shlex.quote(a) for a in sys.argv[1:])
    os.execvp("bash", ["bash", "-lc",
                       f"source {ROS_SETUP} && exec {shlex.quote(_py)} "
                       f"{shlex.quote(os.path.abspath(__file__))} {_args}"])


def die_with_parent() -> None:
    """Ask the kernel to SIGTERM us if our parent goes away.

    The costmap sidecar gets this for free: it writes a frame ~10x a second, so a
    vanished supervisor shows up immediately as EPIPE. This process is SILENT while
    the robot is idle (path and avoid_status only publish during a nav task), so an
    EPIPE may never arrive and a SIGKILLed supervisor would leave a live ROS node
    orphaned indefinitely. PR_SET_PDEATHSIG (=1) closes that hole.

    Best-effort: if ctypes or prctl is unavailable we carry on, since the supervisor
    also terminates us explicitly on the normal path.
    """
    try:
        import ctypes
        import signal
        libc = ctypes.CDLL("libc.so.6", use_errno=True)
        libc.prctl(1, signal.SIGTERM, 0, 0, 0)   # PR_SET_PDEATHSIG
    except Exception:
        pass
    # PDEATHSIG is delivered on the death of the *thread* that forked us, and it is
    # not inherited across the execvp above, so re-arming here (post-bootstrap) is
    # what actually makes it stick. Also handle the case where we were reparented
    # before the call landed.
    if os.getppid() == 1:
        sys.exit("parent already gone")


def build_protobuf_bindings() -> str:
    """protoc the shipped .proto tree into a temp dir and return its path.

    See "WHY protoc RUNS AT STARTUP" above. Generating everything (rather than the
    transitive closure of the three messages we want) is deliberate: protoc does not
    follow imports for code generation, the closure is wide (header -> timestamp ->
    control_source -> ...), and doing the lot costs ~0.2 s.
    """
    if not os.path.isdir(PROTO_SRC):
        raise RuntimeError(f"proto sources not found at {PROTO_SRC}")
    out = tempfile.mkdtemp(prefix="a2navstream-pb-")
    protos = []
    for root, _dirs, files in os.walk(PROTO_SRC):
        for f in files:
            if f.endswith(".proto"):
                protos.append(os.path.relpath(os.path.join(root, f), PROTO_SRC))
    if not protos:
        raise RuntimeError(f"no .proto files under {PROTO_SRC}")
    proc = subprocess.run(
        ["protoc", "-I.", f"--python_out={out}", *sorted(protos)],
        cwd=PROTO_SRC, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"protoc failed: {proc.stderr[-2000:]}")
    # protoc does not emit __init__.py, so the generated tree is not importable
    # as packages until we add them.
    for root, _dirs, _files in os.walk(out):
        init = os.path.join(root, "__init__.py")
        if not os.path.exists(init):
            open(init, "w").close()
    return out


die_with_parent()
_PB_DIR = build_protobuf_bindings()
sys.path.insert(0, _PB_DIR)
sys.path.insert(0, ROSIDL_PY)

import rclpy                                                       # noqa: E402
from rclpy.node import Node                                        # noqa: E402
from rclpy.qos import (QoSProfile, ReliabilityPolicy,              # noqa: E402
                       HistoryPolicy, DurabilityPolicy)
from ros2_plugin_proto.msg import RosMsgWrapper                    # noqa: E402
from aimdk.protocol.pnc import pnc_path_pb2                        # noqa: E402
from aimdk.protocol.pnc import pnc_avoid_status_channel_pb2        # noqa: E402
from nav_msgs.msg import Odometry                                  # noqa: E402
from tf2_msgs.msg import TFMessage                                 # noqa: E402

# Mangled ROS2 topic names -> our short kind. See note 1 in the docstring.
TOPIC_PATH = "/pnc/path_publish/pb_3Aaimdk_2Eprotocol_2EPncPathChannel"
TOPIC_AVOID = "/pnc/avoid_status/pb_3Aaimdk_2Eprotocol_2EPncAvoidStatusChannel"
# Native ROS types — no mangling, no protobuf. See "WHY POSE COMES FROM HERE".
TOPIC_TF = "/tf"
TOPIC_ODOM = "/slam/localization/odometry"

MAP_FRAME = "map"
BASE_FRAME = "base_link"

# Avoid statuses that mean "the route just changed under us". The UI highlights
# these because they are the honest answer to "why did the line move?".
REPLAN_STATUSES = {
    "AvoidStatus_PATH_BLOCK",
    "AvoidStatus_PATH_BLOCK_START_REPLAN",
    "AvoidStatus_PATH_BLOCK_REPLAN_TIMEOUT",
}


def emit(obj: dict, pretty: bool = False) -> None:
    """One JSON object per line on stdout, flushed.

    Flushing matters: the supervisor reads this with readline() and a buffered
    child would make the UI look frozen.
    """
    try:
        if pretty:
            print(json.dumps(obj, indent=2), flush=True)
        else:
            print(json.dumps(obj, separators=(",", ":")), flush=True)
    except BrokenPipeError:
        # Whoever was reading us has gone (supervisor stopped, or a `| head`).
        # That is a normal end of life for a sidecar, not a fault worth a
        # traceback — and exiting here is a second layer of orphan protection
        # alongside PR_SET_PDEATHSIG.
        os._exit(0)


def _payload(msg) -> bytes:
    """Extract the protobuf bytes from a RosMsgWrapper.

    `byte[]` becomes a list of 1-byte `bytes` in rclpy, so bytes(msg.data) raises
    TypeError. Handle the numpy case too in case a future rclpy changes this.
    """
    d = msg.data
    if hasattr(d, "tobytes"):
        return d.tobytes()
    if len(d) and isinstance(d[0], (bytes, bytearray)):
        return b"".join(bytes(x) for x in d)
    return bytes(bytearray(d))


def quat_yaw(q) -> float:
    """Yaw from a ROS quaternion (x,y,z,w), radians CCW about +z."""
    return math.atan2(2.0 * (q.w * q.z + q.x * q.y),
                      1.0 - 2.0 * (q.y * q.y + q.z * q.z))


class NavStream(Node):
    def __init__(self, pretty: bool = False, min_interval: float = 0.0,
                 pose_interval: float = 0.2) -> None:
        super().__init__("a2_nav_stream")
        self.pretty = pretty
        self.min_interval = float(min_interval)
        self.pose_interval = float(pose_interval)
        self._last_path_emit = 0.0
        self._last_pose_emit = 0.0
        self._seq = 0

        # BEST_EFFORT is mandatory — see note 4 in the docstring.
        qos = QoSProfile(reliability=ReliabilityPolicy.BEST_EFFORT,
                         history=HistoryPolicy.KEEP_LAST, depth=5,
                         durability=DurabilityPolicy.VOLATILE)
        self.create_subscription(RosMsgWrapper, TOPIC_PATH, self.on_path, qos)
        self.create_subscription(RosMsgWrapper, TOPIC_AVOID, self.on_avoid, qos)
        # /tf is high-rate (every joint, ~50 Hz) and is the authoritative
        # map->base_link. The odometry topic carries the same pose and is kept as a
        # fallback for the case where slam publishes odom but not the tf link.
        self.create_subscription(TFMessage, TOPIC_TF, self.on_tf, qos)
        self.create_subscription(Odometry, TOPIC_ODOM, self.on_odom, qos)

        emit({"type": "hello",
              "topics": {"path": TOPIC_PATH, "avoid": TOPIC_AVOID,
                         "tf": TOPIC_TF, "odom": TOPIC_ODOM},
              "domain": os.environ.get("ROS_DOMAIN_ID"),
              "note": "path is published only while a nav task is running; "
                      "pose needs converged localization"},
             self.pretty)

    def _emit_pose(self, x: float, y: float, yaw: float, source: str) -> None:
        """Throttled pose emit. /tf arrives ~50 Hz for every link; the UI wants ~5."""
        now = time.time()
        if self.pose_interval and (now - self._last_pose_emit) < self.pose_interval:
            return
        self._last_pose_emit = now
        emit({"type": "pose", "stamp": now, "source": source,
              "pose": {"x": round(x, 4), "y": round(y, 4),
                       "yaw": round(yaw, 5), "stamp": now}}, self.pretty)

    def on_tf(self, msg) -> None:
        for t in msg.transforms:
            if t.header.frame_id == MAP_FRAME and t.child_frame_id == BASE_FRAME:
                tr = t.transform.translation
                self._emit_pose(tr.x, tr.y, quat_yaw(t.transform.rotation), "tf")
                return

    def on_odom(self, msg) -> None:
        """Fallback only — /tf is preferred when both are present.

        Guard on frame_id: an odom-frame message would be the robot's dead-reckoned
        pose, not its position on the map, and drawing that on a map would be wrong.
        """
        if msg.header.frame_id != MAP_FRAME:
            return
        if time.time() - self._last_pose_emit < self.pose_interval * 3:
            return          # /tf is keeping up; don't double-report
        p = msg.pose.pose
        self._emit_pose(p.position.x, p.position.y,
                        quat_yaw(p.orientation), "odometry")

    def on_path(self, msg) -> None:
        """Planned polyline. Published only while a task runs, at planner rate."""
        now = time.time()
        if self.min_interval and (now - self._last_path_emit) < self.min_interval:
            return
        try:
            p = pnc_path_pb2.PncPathChannel()
            p.ParseFromString(_payload(msg))
        except Exception as exc:
            emit({"type": "error", "where": "path", "message": str(exc)}, self.pretty)
            return
        self._last_path_emit = now
        self._seq += 1
        # Send x/y only. z is always ~0 for a ground robot and the UI draws in 2D;
        # halving the payload matters because this can arrive at planner rate.
        emit({"type": "path",
              "seq": self._seq,
              "stamp": now,
              "frame": p.header.frame_id or "map",
              "n": len(p.pose),
              "points": [[round(q.position.x, 4), round(q.position.y, 4)]
                         for q in p.pose]},
             self.pretty)

    def on_avoid(self, msg) -> None:
        """Blocked / replanning / finished events."""
        try:
            a = pnc_avoid_status_channel_pb2.PncAvoidStatusChannel()
            a.ParseFromString(_payload(msg))
        except Exception as exc:
            emit({"type": "error", "where": "avoid", "message": str(exc)}, self.pretty)
            return
        name = pnc_avoid_status_channel_pb2.PncAvoidStatus.Name(a.status)
        emit({"type": "avoid", "stamp": time.time(), "status": name,
              "replanning": name in REPLAN_STATUSES}, self.pretty)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--pretty", action="store_true",
                   help="indent the JSON (for reading it yourself)")
    p.add_argument("--min-path-interval", type=float, default=0.2,
                   help="throttle path frames, seconds (0 = every frame)")
    p.add_argument("--min-pose-interval", type=float, default=0.2,
                   help="throttle pose frames, seconds; /tf arrives ~50 Hz")
    p.add_argument("--domain", default=None, help="ROS_DOMAIN_ID override (default 232)")
    args = p.parse_args()

    rclpy.init()
    node = NavStream(pretty=args.pretty, min_interval=args.min_path_interval,
                     pose_interval=args.min_pose_interval)
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    except rclpy.executors.ExternalShutdownException:
        # The supervisor stops us with SIGTERM when the last viewer leaves.
        # rclpy turns that into this exception; it is a normal exit, not a fault.
        pass
    finally:
        try:
            node.destroy_node()
        except Exception:
            pass
        try:
            rclpy.shutdown()
        except Exception:
            pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
